### ISSUE TITLE
Issue with Firestore

### ISSUE THREAD

**Issue by jobrayan** [sulabh9999/sendMultipleMail#1]
After running `python3 email_sender.py`

**Gives:**

```
creating user at firestore: emailaddres@address [comment: ~replaced just in case~]
Traceback (most recent call last):
  File "/home/gecrator/.local/lib/python3.6/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
 
Process finished with exit code 1
```

I guess the manual is not updated, because there is not test.py script in the root folder `Email-Sender`

PS. JSON was placed on place, `ServiceAccount.json`

**Comment by jobrayan** [comment]
"The project `Project Name` does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=[`Project Name`] to add a Cloud Datastore or Cloud Firestore database

**Comment by jobrayan** [comment]
Once "Added Database - Native" - worked. 

Thank you. 

`Process finished with exit code 0`

**Comment by sulabh9999** [comment]
Thanks, Please feel free to contribute if you find any mistake or enhancement.
